GET http://localhost:3000/users
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Septa",
    "email": "alfauzansepta@gmail.com",
    "username": "septa as",
    "password": "mypassword",
    "profile_pic": "",
    "verified": false
}
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Septa",
    "email": "septagamer@gmail.com",
    "username": "septa keren",
    "password": "mypassword",
    "profile_pic": "",
    "verified": false
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username_email": "alfauzansepta@gmail.com",
    "password": "mypassword"
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username_email": "septa",
    "password": "mypassworda"
}
###
DELETE   http://localhost:3000/users/5f17e89a5551306480b47c3e
###

PUT   http://localhost:3000/users/verify/5f17a884228b4317d554ce3c
###
GET   http://localhost:3000/emails
###
http://localhost:3000/users/verify/5f17e89a5551306480b47c3e