GET http://localhost:4000/users
###
POST http://localhost:4000/users
Content-Type: application/json

{
    "firstName": "Septa",
    "lastName": "Septa",
    "email": "alfauzansepta@gmail.comasdasda",
    "username": "septaalfauzan",
    "password": "mypassword",
    "profile_pic": "",
    "verified": false
}
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Septa",
    "email": "septagamer@gmail.com",
    "username": "septa keren",
    "password": "mypassword",
    "profile_pic": "",
    "verified": false
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username_email": "alfauzansepta@gmail.com",
    "password": "mypassword"
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username_email": "septa",
    "password": "mypassworda"
}
###
DELETE   http://localhost:4000/users/5f1d19f7f66c385fc2065229
###

PUT   http://localhost:3000/users/verify/5f17a884228b4317d554ce3c
###
GET   http://localhost:3000/emails
###
PUT http://localhost:4000/users/verify/5f1d17fef66c385fc2065227